import { GALLERY_ITEMS } from '@/config/content/gallery'
import { MemeConveyor } from '@/ui/MemeConveyor'
import { SectionHeading } from '@/ui/SectionHeading'

/**
 * The evidence reel. All artwork is generated by `npm run assets` from the
 * hand-authored pixel font and sprite grids — nothing here is scraped.
 */
export function Gallery() {
  return (
    <section className="section" id="gallery" aria-labelledby="gallery-title">
      <div className="shell">
        <SectionHeading
          stage="STAGE 06"
          title="Evidence Reel"
          id="gallery-title"
          accent="magenta"
          blurb="Bootleg covers for a game that was never made, for a console that never existed, about a stock that very much does."
        />
      </div>
      <MemeConveyor items={GALLERY_ITEMS} label="Original poster artwork" />
    </section>
  )
}
